CREATE PROCEDURE [SetKnownGoodState]
AS
BEGIN
    ALTER TABLE History DROP CONSTRAINT fk_History_PlayerId;
    ALTER TABLE Performance DROP CONSTRAINT fk_Performance_MatchId;
    ALTER TABLE Performance DROP CONSTRAINT fk_Performance_PlayerId;
    ALTER TABLE Performance DROP CONSTRAINT fk_Performance_PositionId;
    ALTER TABLE Loan DROP CONSTRAINT fk_Loan_ParentClubId;
    ALTER TABLE Loan DROP CONSTRAINT fk_Loan_LoanClubId;
    ALTER TABLE Loan DROP CONSTRAINT fk_Loan_PlayerId;
    ALTER TABLE Match DROP CONSTRAINT fk_Match_HomeClubId;
    ALTER TABLE Match DROP CONSTRAINT fk_Match_VisitingClubId; 
    ALTER TABLE Match DROP CONSTRAINT fk_Match_SeasonId;    
    ALTER TABLE Player DROP CONSTRAINT fk_Player_ClubId;   
    ALTER TABLE Player DROP CONSTRAINT fk_Player_PositionId;
    TRUNCATE TABLE History;
    TRUNCATE TABLE Performance;
    TRUNCATE TABLE Loan;
    TRUNCATE TABLE Match;
    TRUNCATE TABLE Season;
    TRUNCATE TABLE Player;
    TRUNCATE TABLE Club;
    TRUNCATE TABLE Position;
    ALTER TABLE History add CONSTRAINT fk_History_PlayerId
        FOREIGN KEY (PlayerId)
        REFERENCES Player(PlayerId);
    ALTER TABLE Performance ADD CONSTRAINT fk_Performance_MatchId
        foreign key (MatchId)
        REFERENCES Match(MatchId);
    ALTER TABLE Performance ADD CONSTRAINT fk_Performance_PlayerId
        foreign key (PlayerId)
        references Player(PlayerId);
    ALTER TABLE Performance ADD CONSTRAINT fk_Performance_PositionId
        foreign key (PositionId)
        references Position(PositionId);
    ALTER TABLE Loan add CONSTRAINT fk_Loan_ParentClubId
        FOREIGN KEY (ParentClubId)
        REFERENCES Club(ClubId);
    ALTER TABLE Loan ADD CONSTRAINT fk_Loan_LoanClubId
        foreign key (LoanClubId)
        REFERENCES Club(ClubId);
    ALTER TABLE Loan add CONSTRAINT fk_Loan_PlayerId
        FOREIGN KEY (PlayerId)
        REFERENCES Player(PlayerId);
    ALTER TABLE Match ADD CONSTRAINT fk_Match_HomeClubId
        foreign key (HomeClubId)
        REFERENCES Club(ClubId);    
    ALTER TABLE Match ADD CONSTRAINT fk_Match_VisitingClubId
        foreign key (VisitingClubId)
        REFERENCES Club(ClubId);   
    ALTER TABLE Match ADD CONSTRAINT fk_Match_SeasonId
        foreign key (SeasonId)
        REFERENCES Season(SeasonId);   
    ALTER TABLE Player ADD CONSTRAINT fk_Player_ClubId
        foreign key (ClubId)
        REFERENCES Club(ClubId);
    ALTER TABLE Player ADD CONSTRAINT fk_Player_PositionId
        foreign key (PositionId)
        REFERENCES Position(PositionId);

    INSERT into Position(PositionName) 
        VALUES ('Goalkeeper'), ('Defender'),('Midfielder'),('Forward');
insert into Club ([Name], FoundingDate, City) values ('Bush dog', '1956-11-20', 'Sakassou');
insert into Club ([Name], FoundingDate, City) values ('Cuis', '1949-12-11', 'Zbraslav');
insert into Club ([Name], FoundingDate, City) values ('Gulls (unidentified)', '1999-01-29', 'Kudang');
insert into Club ([Name], FoundingDate, City) values ('Chameleon (unidentified)', '1967-04-13', 'Canis');
insert into Club ([Name], FoundingDate, City) values ('Lion, steller''s sea', '1970-01-27', 'Tadabliro');
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (2, 4, 'Phil', 'Gallihawk', '2034-08-31', 0, 1);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (5, 4, 'Meghann', 'Shippey', '2033-04-06', 1, 0);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (1, 4, 'Nicolea', 'Mitroshinov', '2031-08-09', 1, 0);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (5, 1, 'Nissy', 'Wedgwood', '2020-03-29', 0, 1);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (3, 1, 'Granthem', 'Baigrie', '2074-01-31', 1, 0);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (2, 3, 'Paula', 'Noot', '2068-01-20', 1, 0);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (4, 3, 'Cornall', 'Mayman', '2025-05-05', 1, 0);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (4, 2, 'Edgar', 'Bartley', '2010-06-12', 1, 0);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (5, 4, 'Hannah', 'Langran', '2083-09-09', 1, 1);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (4, 2, 'Glad', 'Sustins', '2034-01-17', 1, 0);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (3, 3, 'Killie', 'Scrigmour', '2081-06-27', 0, 0);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (3, 1, 'Merrill', 'Mewhirter', '2021-08-22', 1, 0);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (3, 3, 'Frederica', 'Gurry', '2069-09-22', 0, 0);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (3, 3, 'Janka', 'Letson', '2029-04-05', 0, 0);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (5, 1, 'Miguela', 'Kilshall', '2087-03-02', 1, 0);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (2, 3, 'Adriaens', 'Jeenes', '2022-04-13', 1, 0);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (1, 4, 'Zarah', 'Benedite', '2071-07-15', 1, 0);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (2, 3, 'Gelya', 'Howton', '2010-04-20', 1, 0);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (3, 1, 'Keen', 'Fancourt', '2016-05-28', 0, 0);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (2, 2, 'Mady', 'Baumer', '2019-03-22', 1, 0);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (5, 2, 'Skell', 'Ramsdell', '2062-07-24', 1, 0);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (4, 2, 'Portia', 'Monier', '2077-12-21', 1, 0);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (3, 1, 'Beltran', 'Barrett', '2072-06-18', 1, 0);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (5, 2, 'Rosabel', 'Roman', '2049-05-29', 1, 1);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (4, 1, 'Hinze', 'Lamberti', '2014-12-23', 1, 0);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (4, 3, 'Sukey', 'Escofier', '2069-06-21', 1, 0);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (2, 3, 'Koo', 'Brighty', '2082-01-19', 1, 0);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (4, 2, 'Adamo', 'Dondon', '2017-05-19', 1, 0);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (1, 1, 'Loella', 'Conquer', '2071-10-26', 1, 0);
insert into Player (ClubId, PositionId, FirstName, LastName, DateOfBirth, IsActive, IsOnLoan) values (3, 1, 'Roch', 'Rizzello', '2045-07-28', 1, 0);
insert into Season ([Year]) values ('2017-2018');
insert into Season ([Year]) values ('2018-2019');
insert into Season ([Year]) values ('2019-2020');
insert into Season ([Year]) values ('2020-2021');
insert into Season ([Year]) values ('2021-2022');
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (1, 2, 5, 34572, 3, 7);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (1, 3, 1, 36285, 17, 20);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (3, 5, 2, null, null, null);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (4, 1, 2, 35655, 14, 5);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (5, 2, 2, 35799, 19, 18);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (1, 3, 4, 35241, 13, 15);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (1, 5, 3, 36318, 19, 10);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (3, 3, 4, 36320, 10, 10);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (2, 4, 5, 35617, 14, 8);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (3, 2, 1, 36691, 14, 5);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (3, 2, 5, 36973, 4, 15);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (4, 3, 1, 37047, 10, 3);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (1, 3, 2, 34601, 17, 5);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (4, 2, 3, 37365, 6, 19);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (3, 5, 1, 37728, 13, 7);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (4, 2, 2, 36327, 4, 3);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (3, 3, 5, 35146, 14, 1);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (1, 2, 4, 37666, 4, 9);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (3, 4, 1, 35052, 1, 6);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (1, 5, 3, 35760, 8, 14);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (5, 2, 4, null, null, null);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (4, 1, 4, 36187, 15, 18);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (1, 5, 1, 34627, 9, 3);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (1, 4, 3, 36647, 18, 4);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (2, 4, 2, 34461, 0, 0);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (2, 4, 1, 36307, 20, 20);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (3, 2, 3, 37423, 20, 11);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (2, 3, 2, 34276, 10, 3);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (1, 2, 4, 38322, 18, 3);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (5, 2, 3, 37811, 17, 18);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (4, 1, 2, 34649, 19, 1);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (5, 1, 2, 35097, 15, 19);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (3, 1, 3, 37727, 13, 4);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (3, 5, 1, 35454, 1, 13);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (2, 3, 1, 38232, 12, 1);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (3, 5, 5, 35187, 13, 3);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (5, 5, 4, 36432, 8, 20);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (3, 1, 1, 36150, 0, 18);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (2, 2, 4, 36240, 17, 8);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (1, 3, 4, 37527, 15, 12);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (1, 2, 3, 35452, 8, 2);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (3, 1, 2, 38438, 14, 3);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (4, 2, 1, 34452, 6, 17);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (4, 3, 4, 37534, 16, 10);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (4, 3, 5, 34642, 9, 9);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (4, 5, 2, null, null, null);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (5, 2, 1, 38295, 4, 11);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (4, 1, 3, 38122, 6, 0);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (1, 5, 2, 36145, 8, 0);
insert into Match (HomeClubId, VisitingClubId, SeasonId, NumberOfAttendees, HomeScore, AwayScore) values (1, 4, 2, 34305, 1, 13);
insert into Loan (ParentClubId, LoanClubId, PlayerId, LoanDuration, LoanStart) values (4, 2, 4, 3, '2021-10-18');
insert into Loan (ParentClubId, LoanClubId, PlayerId, LoanDuration, LoanStart) values (4, 2, 4, 4, '2018-08-16');
insert into Loan (ParentClubId, LoanClubId, PlayerId, LoanDuration, LoanStart) values (2, 4, 3, 4, '2021-11-21');
insert into Loan (ParentClubId, LoanClubId, PlayerId, LoanDuration, LoanStart) values (4, 3, 2, 1, '2019-05-06');
insert into Loan (ParentClubId, LoanClubId, PlayerId, LoanDuration, LoanStart) values (4, 5, 1, 2, '2021-03-17');
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (28, 10, 2, 4, 5, 1, 0, 6, 9, 1, 8, 6, 10, 1, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (35, 4, 2, 8, 6, 1, 8, 10, 6, 7, 7, 8, 1, 3, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (17, 15, 4, 7, 8, 2, 0, 10, 8, 4, 10, 7, 8, 8, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (8, 6, 4, 6, 1, 8, 8, 2, 3, 2, 3, 9, 10, 1, 0);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (34, 13, 1, 1, 10, 6, 6, 2, 8, 3, 7, 5, 0, 1, 0);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (21, 20, 4, 6, 3, 2, 9, 7, 8, 10, 3, 0, 4, 8, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (34, 6, 1, 4, 8, 4, 7, 0, 2, 7, 6, 2, 0, 5, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (20, 2, 4, 7, 3, 2, 3, 7, 0, 4, 4, 1, 0, 3, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (12, 12, 3, 7, 2, 8, 0, 8, 0, 9, 5, 3, 10, 9, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (2, 15, 2, 7, 7, 3, 2, 10, 6, 1, 3, 7, 9, 10, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (34, 20, 3, 3, 10, 6, 3, 3, 2, 3, 10, 9, 0, 9, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (21, 10, 2, 5, 9, 4, 3, 9, 8, 3, 7, 7, 0, 5, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (26, 13, 1, 3, 0, 4, 1, 10, 2, 0, 10, 1, 6, 10, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (31, 6, 1, 9, 2, 6, 0, 0, 10, 8, 9, 5, 7, 9, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (40, 25, 2, 3, 2, 7, 0, 3, 0, 5, 10, 9, 0, 4, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (24, 10, 1, 8, 5, 7, 8, 3, 5, 1, 10, 8, 4, 10, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (32, 3, 4, 2, 3, 3, 5, 10, 5, 9, 9, 5, 9, 1, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (21, 3, 1, 6, 0, 6, 1, 8, 4, 6, 3, 10, 3, 0, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (11, 21, 2, 6, 10, 1, 10, 9, 1, 9, 0, 2, 6, 5, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (1, 15, 3, 4, 1, 4, 4, 10, 0, 4, 6, 1, 7, 8, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (37, 16, 3, 4, 7, 0, 3, 0, 10, 1, 4, 9, 2, 8, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (24, 20, 3, 3, 4, 9, 9, 5, 3, 8, 10, 8, 0, 1, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (17, 20, 4, 0, 1, 1, 5, 7, 9, 8, 9, 1, 0, 10, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (36, 14, 4, 4, 3, 9, 1, 5, 9, 2, 0, 4, 8, 4, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (40, 17, 4, 6, 8, 5, 8, 6, 9, 2, 2, 2, 5, 0, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (35, 19, 1, 3, 5, 3, 9, 3, 1, 1, 2, 5, 4, 10, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (39, 9, 4, 3, 6, 3, 1, 10, 6, 7, 3, 3, 6, 10, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (18, 3, 1, 0, 7, 2, 4, 8, 4, 0, 1, 1, 2, 8, 0);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (9, 8, 1, 2, 4, 6, 1, 1, 5, 2, 0, 5, 3, 4, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (8, 4, 4, 0, 3, 4, 7, 3, 9, 10, 5, 3, 10, 1, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (22, 19, 2, 5, 3, 4, 7, 6, 5, 7, 6, 7, 6, 0, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (13, 20, 3, 2, 9, 3, 0, 3, 8, 0, 10, 9, 10, 5, 0);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (16, 21, 4, 3, 10, 4, 8, 7, 10, 10, 8, 7, 0, 10, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (25, 23, 1, 5, 1, 0, 1, 2, 5, 1, 8, 2, 3, 3, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (12, 16, 1, 5, 6, 1, 1, 8, 1, 0, 5, 3, 1, 6, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (36, 8, 1, 0, 0, 9, 4, 3, 10, 4, 5, 6, 5, 0, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (13, 6, 2, 8, 5, 2, 7, 6, 7, 4, 4, 1, 4, 7, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (4, 12, 1, 3, 0, 6, 3, 1, 1, 10, 5, 5, 6, 1, 0);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (15, 10, 3, 3, 6, 3, 10, 1, 2, 2, 3, 5, 4, 10, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (5, 1, 1, 3, 7, 9, 6, 2, 0, 2, 8, 1, 8, 10, 0);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (33, 3, 4, 3, 1, 0, 2, 9, 4, 6, 10, 8, 9, 6, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (15, 12, 2, 6, 3, 9, 1, 7, 3, 6, 6, 9, 9, 9, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (35, 25, 3, 9, 9, 9, 8, 7, 4, 5, 10, 3, 3, 2, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (6, 4, 3, 6, 7, 8, 1, 7, 2, 3, 7, 0, 3, 2, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (24, 3, 4, 3, 9, 2, 10, 6, 6, 4, 7, 9, 1, 4, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (4, 10, 2, 1, 3, 2, 8, 10, 7, 3, 4, 9, 2, 8, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (3, 17, 4, 10, 2, 4, 2, 8, 0, 4, 4, 3, 6, 5, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (13, 16, 3, 7, 2, 1, 1, 5, 8, 3, 7, 8, 2, 9, 0);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (19, 3, 1, 10, 5, 9, 3, 0, 9, 9, 2, 7, 8, 0, 0);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (17, 25, 4, 7, 0, 1, 6, 1, 6, 3, 5, 2, 7, 0, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (2, 8, 4, 0, 4, 5, 8, 5, 4, 5, 2, 5, 9, 8, 0);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (8, 25, 2, 7, 2, 5, 0, 3, 1, 4, 10, 0, 2, 7, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (20, 11, 1, 6, 9, 1, 0, 10, 4, 4, 10, 7, 7, 3, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (4, 25, 3, 0, 2, 10, 8, 9, 1, 1, 6, 5, 4, 5, 0);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (29, 8, 4, 4, 10, 5, 0, 0, 10, 8, 2, 7, 5, 6, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (4, 16, 4, 7, 10, 8, 9, 9, 3, 2, 1, 9, 9, 10, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (7, 25, 3, 7, 7, 3, 2, 8, 2, 1, 5, 0, 4, 3, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (3, 11, 4, 4, 6, 6, 5, 5, 10, 9, 5, 1, 1, 0, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (37, 9, 1, 3, 3, 10, 2, 10, 0, 7, 3, 4, 8, 0, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (6, 18, 1, 2, 5, 2, 0, 9, 2, 1, 4, 1, 10, 0, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (19, 18, 1, 2, 0, 3, 5, 6, 0, 2, 1, 0, 7, 7, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (24, 15, 3, 8, 8, 4, 6, 2, 3, 7, 2, 4, 0, 0, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (23, 8, 1, 6, 9, 2, 5, 6, 2, 6, 9, 10, 3, 6, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (36, 22, 3, 3, 3, 3, 8, 7, 10, 4, 10, 1, 10, 0, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (9, 18, 4, 1, 0, 9, 0, 0, 1, 9, 3, 8, 5, 3, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (16, 19, 3, 10, 0, 7, 10, 1, 9, 4, 1, 9, 9, 1, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (21, 11, 4, 1, 7, 6, 3, 4, 9, 8, 5, 9, 8, 4, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (25, 15, 3, 9, 9, 1, 3, 0, 8, 7, 2, 6, 8, 6, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (25, 11, 1, 2, 10, 4, 5, 0, 6, 6, 2, 8, 4, 7, 0);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (13, 24, 4, 3, 5, 10, 6, 5, 7, 10, 2, 0, 2, 10, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (35, 11, 3, 5, 6, 6, 3, 9, 5, 4, 4, 7, 4, 7, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (22, 4, 3, 3, 2, 5, 7, 8, 8, 8, 9, 3, 6, 5, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (17, 7, 4, 9, 4, 4, 1, 7, 5, 2, 7, 5, 4, 2, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (10, 21, 2, 6, 0, 5, 10, 6, 1, 0, 2, 8, 8, 3, 0);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (3, 19, 2, 2, 1, 9, 7, 10, 7, 6, 5, 2, 3, 0, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (37, 19, 2, 6, 5, 10, 5, 2, 3, 0, 5, 5, 1, 2, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (22, 7, 3, 6, 5, 3, 3, 8, 7, 4, 9, 2, 1, 9, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (28, 15, 2, 6, 0, 9, 1, 10, 8, 0, 4, 3, 1, 2, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (2, 22, 4, 10, 6, 3, 2, 6, 3, 0, 1, 4, 5, 10, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (2, 20, 4, 7, 3, 2, 2, 6, 10, 9, 10, 7, 6, 10, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (4, 11, 4, 4, 10, 5, 9, 10, 5, 10, 6, 3, 2, 6, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (35, 14, 1, 8, 9, 3, 2, 2, 2, 3, 6, 6, 2, 7, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (40, 9, 1, 10, 10, 8, 7, 10, 10, 9, 5, 1, 8, 10, 0);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (6, 17, 1, 2, 7, 8, 6, 0, 5, 6, 9, 7, 3, 0, 0);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (5, 25, 1, 2, 5, 4, 3, 9, 4, 3, 3, 10, 9, 7, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (1, 23, 3, 1, 8, 9, 0, 1, 5, 5, 6, 7, 4, 0, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (36, 17, 3, 9, 10, 8, 7, 4, 10, 3, 8, 4, 3, 4, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (28, 21, 3, 7, 6, 6, 10, 6, 1, 7, 8, 0, 7, 10, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (16, 17, 3, 10, 0, 2, 1, 2, 6, 5, 7, 1, 9, 3, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (18, 10, 4, 0, 3, 5, 1, 7, 0, 9, 8, 10, 10, 5, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (5, 22, 1, 4, 9, 8, 0, 7, 7, 3, 2, 2, 9, 2, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (3, 25, 1, 10, 8, 4, 5, 1, 6, 1, 7, 0, 7, 5, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (1, 12, 1, 8, 0, 4, 0, 5, 2, 3, 9, 4, 10, 0, 0);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (18, 25, 3, 9, 0, 3, 10, 0, 4, 8, 4, 9, 10, 10, 0);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (20, 17, 2, 2, 2, 8, 8, 8, 5, 0, 6, 4, 2, 7, 1);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (7, 23, 2, 9, 1, 0, 10, 10, 9, 3, 5, 3, 6, 2, 0);
insert into Performance (MatchId, PlayerId, PositionId, ShotsOnTarget, Fouls, Assists, Saves, Shots, Passes, PassesCompleted, Dribbles, DribblesSucceeded, Tackles, TacklesSucceeded, CleanSheet) values (21, 15, 1, 2, 6, 1, 9, 1, 9, 6, 2, 10, 0, 9, 1);
insert into History (PlayerId, HistoryEntry) values (25, 'Multi-tiered optimal throughput');
insert into History (PlayerId, HistoryEntry) values (6, 'Team-oriented next generation infrastructure');
insert into History (PlayerId, HistoryEntry) values (13, 'Assimilated even-keeled architecture');
insert into History (PlayerId, HistoryEntry) values (3, 'De-engineered regional middleware');
insert into History (PlayerId, HistoryEntry) values (7, 'Enterprise-wide solution-oriented parallelism');
insert into History (PlayerId, HistoryEntry) values (14, 'Switchable zero defect contingency');
insert into History (PlayerId, HistoryEntry) values (19, 'Implemented 6th generation structure');
insert into History (PlayerId, HistoryEntry) values (12, 'Monitored transitional support');
insert into History (PlayerId, HistoryEntry) values (16, 'Reduced transitional matrix');
insert into History (PlayerId, HistoryEntry) values (20, 'Robust modular extranet');
insert into History (PlayerId, HistoryEntry) values (17, 'Inverse explicit process improvement');
insert into History (PlayerId, HistoryEntry) values (1, 'Open-architected 24/7 encryption');
insert into History (PlayerId, HistoryEntry) values (4, 'Quality-focused stable monitoring');
insert into History (PlayerId, HistoryEntry) values (5, 'Enterprise-wide motivating extranet');
insert into History (PlayerId, HistoryEntry) values (2, 'Streamlined uniform Graphical User Interface');
insert into History (PlayerId, HistoryEntry) values (14, 'Team-oriented optimal project');
insert into History (PlayerId, HistoryEntry) values (18, 'Focused optimal superstructure');
insert into History (PlayerId, HistoryEntry) values (2, 'Business-focused uniform contingency');
insert into History (PlayerId, HistoryEntry) values (3, 'Intuitive directional standardization');
insert into History (PlayerId, HistoryEntry) values (23, 'Monitored mobile success');
insert into History (PlayerId, HistoryEntry) values (4, 'Seamless bottom-line pricing structure');
insert into History (PlayerId, HistoryEntry) values (25, 'Re-engineered disintermediate alliance');
insert into History (PlayerId, HistoryEntry) values (25, 'Assimilated foreground success');
insert into History (PlayerId, HistoryEntry) values (2, 'Open-architected upward-trending archive');
insert into History (PlayerId, HistoryEntry) values (3, 'Digitized object-oriented support');
insert into History (PlayerId, HistoryEntry) values (9, 'Centralized actuating leverage');
insert into History (PlayerId, HistoryEntry) values (16, 'Right-sized transitional budgetary management');
insert into History (PlayerId, HistoryEntry) values (19, 'Multi-tiered methodical function');
insert into History (PlayerId, HistoryEntry) values (12, 'Up-sized bi-directional open architecture');
insert into History (PlayerId, HistoryEntry) values (22, 'Re-engineered disintermediate contingency');
insert into History (PlayerId, HistoryEntry) values (16, 'Synergized discrete budgetary management');
insert into History (PlayerId, HistoryEntry) values (14, 'Grass-roots asymmetric success');
insert into History (PlayerId, HistoryEntry) values (11, 'Function-based transitional architecture');
insert into History (PlayerId, HistoryEntry) values (8, 'Object-based demand-driven application');
insert into History (PlayerId, HistoryEntry) values (6, 'Decentralized zero tolerance database');
insert into History (PlayerId, HistoryEntry) values (12, 'Compatible multi-tasking approach');
insert into History (PlayerId, HistoryEntry) values (24, 'Enhanced 24 hour Graphical User Interface');
insert into History (PlayerId, HistoryEntry) values (14, 'Enterprise-wide client-driven workforce');
insert into History (PlayerId, HistoryEntry) values (9, 'Managed optimizing hub');
insert into History (PlayerId, HistoryEntry) values (10, 'Reactive asymmetric orchestration');
insert into History (PlayerId, HistoryEntry) values (19, 'Extended eco-centric focus group');
insert into History (PlayerId, HistoryEntry) values (24, 'Profound client-server alliance');
insert into History (PlayerId, HistoryEntry) values (9, 'Cross-group contextually-based structure');
insert into History (PlayerId, HistoryEntry) values (10, 'Synergized grid-enabled help-desk');
insert into History (PlayerId, HistoryEntry) values (22, 'Right-sized uniform approach');
insert into History (PlayerId, HistoryEntry) values (17, 'Synergized multi-tasking matrices');
insert into History (PlayerId, HistoryEntry) values (8, 'Devolved grid-enabled groupware');
insert into History (PlayerId, HistoryEntry) values (10, 'Profound 4th generation open architecture');
insert into History (PlayerId, HistoryEntry) values (18, 'Stand-alone leading edge alliance');
insert into History (PlayerId, HistoryEntry) values (11, 'Optional cohesive ability');
insert into History (PlayerId, HistoryEntry) values (6, 'Multi-lateral transitional access');
insert into History (PlayerId, HistoryEntry) values (17, 'Pre-emptive asynchronous internet solution');
insert into History (PlayerId, HistoryEntry) values (17, 'Realigned bi-directional approach');
insert into History (PlayerId, HistoryEntry) values (7, 'Focused methodical circuit');
insert into History (PlayerId, HistoryEntry) values (7, 'Front-line context-sensitive knowledge base');
insert into History (PlayerId, HistoryEntry) values (19, 'Re-contextualized modular access');
insert into History (PlayerId, HistoryEntry) values (16, 'Re-contextualized solution-oriented algorithm');
insert into History (PlayerId, HistoryEntry) values (21, 'Customizable static artificial intelligence');
insert into History (PlayerId, HistoryEntry) values (2, 'Optional zero tolerance utilisation');
insert into History (PlayerId, HistoryEntry) values (22, 'Object-based multimedia website');
insert into History (PlayerId, HistoryEntry) values (9, 'Streamlined human-resource initiative');
insert into History (PlayerId, HistoryEntry) values (4, 'Fully-configurable uniform complexity');
insert into History (PlayerId, HistoryEntry) values (7, 'Face to face methodical task-force');
insert into History (PlayerId, HistoryEntry) values (16, 'Customer-focused static structure');
insert into History (PlayerId, HistoryEntry) values (21, 'Distributed explicit installation');
insert into History (PlayerId, HistoryEntry) values (12, 'Cross-group client-server support');
insert into History (PlayerId, HistoryEntry) values (11, 'User-centric high-level knowledge base');
insert into History (PlayerId, HistoryEntry) values (8, 'Sharable eco-centric initiative');
insert into History (PlayerId, HistoryEntry) values (19, 'Reverse-engineered multi-tasking productivity');
insert into History (PlayerId, HistoryEntry) values (4, 'Distributed tertiary definition');
insert into History (PlayerId, HistoryEntry) values (19, 'Synergized stable interface');
insert into History (PlayerId, HistoryEntry) values (22, 'Configurable object-oriented attitude');
insert into History (PlayerId, HistoryEntry) values (1, 'Diverse directional instruction set');
insert into History (PlayerId, HistoryEntry) values (21, 'Re-contextualized executive archive');
insert into History (PlayerId, HistoryEntry) values (5, 'Organized client-server complexity');
insert into History (PlayerId, HistoryEntry) values (12, 'Function-based motivating firmware');
insert into History (PlayerId, HistoryEntry) values (7, 'Grass-roots uniform frame');
insert into History (PlayerId, HistoryEntry) values (9, 'Inverse content-based Graphical User Interface');
insert into History (PlayerId, HistoryEntry) values (22, 'Fully-configurable needs-based project');
insert into History (PlayerId, HistoryEntry) values (24, 'Programmable incremental toolset');
insert into History (PlayerId, HistoryEntry) values (7, 'Multi-tiered scalable ability');
insert into History (PlayerId, HistoryEntry) values (20, 'Re-contextualized optimal framework');
insert into History (PlayerId, HistoryEntry) values (6, 'Implemented composite product');
insert into History (PlayerId, HistoryEntry) values (3, 'Managed local database');
insert into History (PlayerId, HistoryEntry) values (25, 'Profound clear-thinking analyzer');
insert into History (PlayerId, HistoryEntry) values (3, 'Up-sized holistic implementation');
insert into History (PlayerId, HistoryEntry) values (8, 'Grass-roots radical product');
insert into History (PlayerId, HistoryEntry) values (13, 'Front-line attitude-oriented encryption');
insert into History (PlayerId, HistoryEntry) values (24, 'Realigned local challenge');
insert into History (PlayerId, HistoryEntry) values (10, 'Automated exuding solution');
insert into History (PlayerId, HistoryEntry) values (10, 'Distributed solution-oriented adapter');
insert into History (PlayerId, HistoryEntry) values (6, 'Total composite algorithm');
insert into History (PlayerId, HistoryEntry) values (23, 'Diverse bi-directional encryption');
insert into History (PlayerId, HistoryEntry) values (10, 'Profit-focused solution-oriented productivity');
insert into History (PlayerId, HistoryEntry) values (22, 'Automated content-based migration');
insert into History (PlayerId, HistoryEntry) values (18, 'Mandatory user-facing policy');
insert into History (PlayerId, HistoryEntry) values (9, 'Synergistic interactive product');
insert into History (PlayerId, HistoryEntry) values (11, 'Visionary content-based encoding');
insert into History (PlayerId, HistoryEntry) values (3, 'Streamlined exuding migration');
insert into History (PlayerId, HistoryEntry) values (12, 'Cross-platform client-server strategy');
END