insert into Club ([Name], FoundingDate, City) values ('Manchester City FC', 1880, 'Manchester');
insert into Club ([Name], FoundingDate, City) values ('Manchester United FC', 1878, 'Manchester');
insert into Club ([Name], FoundingDate, City) values ('Liverpool FC', 1892, 'Liverpool');
insert into Club ([Name], FoundingDate, City) values ('Chelsea FC', 1905, 'London');
insert into Club ([Name], FoundingDate, City) values ('Southampton FC', 1885, 'Southampton');
insert into Club ([Name], FoundingDate, City) values ('Crystal Palace FC', 1905, 'London');

insert into Position (PositionName) values ('Forward');
insert into Position (PositionName) values ('Midfielder');
insert into Position (PositionName) values ('Defender');
insert into Position (PositionName) values ('GoalKeeper');

insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Ederson', 'Santana de Moraes', '1993-08-17', 1, 4, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Ruben', 'Dias', '1997-05-14', 1, 3, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Joao', 'Cancelo', '1994-05-27', 1, 3, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Rodrigo', 'Cascante', '1996-06-22', 1, 2, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Kevin', 'De Bruyne', '1991-06-28', 1, 2, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Phil', 'Foden', '2000-05-28', 1, 1, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('David', 'de Gea', '1990-11-07', 2, 4, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Raphael', 'Varane', '1993-04-25', 2, 3, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Diogo', 'Dalot', '1999-03-18', 2, 3, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Paul', 'Pogba', '1993-03-15', 2, 2, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Bruno', 'Fernandes', '1994-09-08', 2, 2, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Cristiano', 'Ronaldo', '1985-02-05', 2, 1, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Alisson', 'Becker', '1992-10-02', 3, 4, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Virgil', 'van Dijk', '1991-07-08', 3, 3, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Trent', 'Alexander-Arnold', '1998-10-07', 3, 3, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Thiago', 'Alcantara', '1991-04-11', 3, 2, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Sadio', 'Mane', '1992-04-10', 3, 1, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Mohamed', 'Salah', '1992-06-15', 3, 1, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Edouard', 'Mendy', '1992-03-01', 4, 4, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Reece', 'James', '1999-12-08', 4, 3, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Thiago', 'Silva', '1984-09-22', 4, 3, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Benjamin', 'Chilwell', '1996-12-21', 4, 3, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Mason', 'Mount', '1999-01-10', 4, 2, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Kai', 'Havertz', '1999-06-11', 4, 1, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Fraser', 'Forster', '1988-03-17', 5, 4, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Mohammed', 'Salisu', '1999-04-17', 5, 3, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Valentino', 'Livramento', '2002-11-12', 5, 3, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('James', 'Ward-Prowse', '1994-11-01', 5, 2, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Oriol', 'Romeu', '1991-09-24', 5, 2, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Armando', 'Broja', '2001-09-10', 5, 1, 1, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Vicente', 'Guaita', '1987-01-10', 6, 4, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Marc', 'Guehi', '2000-07-13', 6, 3, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Joachim', 'Andersen', '1996-05-31', 6, 3, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Conor', 'Gallagher', '2000-02-06', 6, 2, 1, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Wilfried', 'Zaha', '1992-11-10', 6, 1, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Odsonne', 'Edouard', '1998-01-16', 6, 1, 0, 1);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Vincent', 'Kompany', '1986-04-10', 1, 3, 0, 0);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Sergio', 'Aguero', '1988-06-02', 1, 1, 0, 0);
insert into Player (FirstName, LastName, DateOfBirth, ClubId, PositionId, IsOnLoan, IsActive) values ('Frank', 'Lampard', '1978-06-20', 4, 2, 0, 0);

insert into Season (NumberOfGames, [Year]) values ('2020-2021');